
kind: pipeline
type: docker
name: product-service-build-arm

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: arm

steps:
- name: build_and_publish-arm
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.product-service
    username:
      from_secret:  dockerhub_username 
    password:
      from_secret:  dockerhub_pass
    tags: ${DRONE_BUILD_NUMBER}-arm32v7
- name: git-clone
  image:  alpine/git
  environment:
    SSH_KEY:
      from_secret:  SSH_KEY
    SSH_HOST:
      from_secret:  SSH_HOST
    SSH_PORT:
      from_secret:  SSH_PORT
  commands:
    - mkdir $HOME/.ssh && echo "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
    - |
      [[ -n "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan -p $${SSH_PORT} $${SSH_HOST} >> $HOME/.ssh/known_hosts
    - |
      [[ -z "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan $${SSH_HOST} >> $HOME/.ssh/known_hosts- echo $SSH_KEY > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - git clone ssh://git@192.168.1.110:222/Baja-KS/WebshopAPI-helm.git
- name: change-img-version
  image:  linuxserver/yq:arm32v7-latest
  commands: 
    - TAG=${DRONE_BUILD_NUMBER}-arm32v7 yq -i -y '.microservice.deployment.tag = "${DRONE_BUILD_NUMBER}-arm32v7" ' WebshopAPI-helm/product/values.yaml
- name: git-push
  image:  alpine/git
  environment:
    SSH_KEY:
      from_secret:  SSH_KEY
    SSH_HOST:
      from_secret:  SSH_HOST
    SSH_PORT:
      from_secret:  SSH_PORT

  commands:
    - mkdir $HOME/.ssh && echo "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
    - |
      [[ -n "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan -p $${SSH_PORT} $${SSH_HOST} >> $HOME/.ssh/known_hosts
    - |
      [[ -z "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan $${SSH_HOST} >> $HOME/.ssh/known_hosts- echo $SSH_KEY > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - cd WebshopAPI-helm
    - git add product/values.yaml
    - git commit -m "Change image version to ${DRONE_BUILD_NUMBER}"
    - git push origin master


---


kind: pipeline
type: docker
name: product-service-build-amd64

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: amd64

steps:
  - name: build_and_publish-amd64
    image:  plugins/docker
    settings:
      repo: bajaks/webshop-api-microservices.product-service
      username:
        from_secret:  dockerhub_username 
      password:
        from_secret:  dockerhub_pass
      tags: ${DRONE_BUILD_NUMBER}-amd64
