name: Product-Svc-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login to docker hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: "Docker build with build number tag"
        run: docker build -t bajaks/product-microservice:${{ github.run_number }} .
      - name: "Docker push with build number"
        run: docker push bajaks/product-microservice:${{ github.run_number }}
      - name: "Docker tag latest"
        run: docker tag bajaks/product-microservice bajaks/authentication-microservice:latest
      - name: "Docker push with latest tag"
        run: docker push bajaks/product-microservice:latest
